# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "JFknJb+purjGIPuKNWFBPlsSLX6KohuYmYV4dmisIhjkeFhhXFQNmoabYQ6D+r/mWYPWiNnohoTSyKv8gjj6eC1SbXb+f2dEXHrmAwr36Enbp2tV0XLx7V2KHZzUmKeJxOSwnNUVZxmSvzVbuiDodtU1PJ2YPK0CM0KF/J+wePA="

addons:
  apt:
    packages:
      - tree
      - libconfuse-dev
  coverity_scan:
    project:
      name: "troglobit/inadyn"
      description: "Inadyn | Small and Simple DDNS Client"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command:   "make clean all"
    branch_pattern: dev

script:
  - ./autogen.sh
  - ./configure --disable-silent-rules --prefix=
  - make clean
  - make -j5
  - ./configure --disable-silent-rules --prefix= --enable-openssl
  - make clean
  - make -j5
  - DESTDIR=~/tmp make install
  - tree ~/tmp
  - ldd ~/tmp/sbin/inadyn
  - ~/tmp/sbin/inadyn -h
