# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We need to install libConfuse, so we cannot use dockerized build
sudo: true

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "JFknJb+purjGIPuKNWFBPlsSLX6KohuYmYV4dmisIhjkeFhhXFQNmoabYQ6D+r/mWYPWiNnohoTSyKv8gjj6eC1SbXb+f2dEXHrmAwr36Enbp2tV0XLx7V2KHZzUmKeJxOSwnNUVZxmSvzVbuiDodtU1PJ2YPK0CM0KF/J+wePA="

addons:
  coverity_scan:
    project:
      name: "troglobit/inadyn"
      description: "Inadyn | Small and Simple DDNS Client"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command:   "make"
    branch_pattern: dev

script:
  - sudo apt-get install libconfuse-dev
  - ./autogen.sh
  - ./configure
  - make
